[tool.poetry]
name = "cve-forge"
version = "0.1.0"
description = "Utility tool for pentesting, cracking, hacking and more..."
authors = ["Esteban Chacon <etherbeing99@proton.me>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
prompt-toolkit = "^3.0.48"
sqlalchemy = "^2.0.36"
pydantic = "^2.10.3"
scapy = "^2.6.1"
requests = "^2.32.3"
rich = "^13.9.4"
psutil = "^6.1.0"
watchdog = "^6.0.0"
pathspec = "^0.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
